=== devzero-inc/workspace-recipe-library/schemas/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "cover_image": {
      "type": "string"
    },
    "repos": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "repo_url": {
            "type": "string"
          }
        },
        "required": ["name", "repo_url"]
      }
    },
    "author": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": ["name"]
    },
    "packages": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "commands": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "shell": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "directory": {
            "type": "string"
          }
        }
      }
    }
  },
  "required": [
    "id",
    "name",
    "description",
    "cover_image",
    "repos",
    "author",
    "packages",
    "commands"
  ]
}

=== devzero-inc/workspace-recipe-library/workspaces/sample3.json
{
  "id": "3",
  "name": "Recipe 3",
  "description": "This is a fantastic recipe for something",
  "cover_image": "https://placekitten.com/700/400",
  "repos": [
    {
      "name": "devinfra-agent",
      "repo_url": "https://github.com/devzero-inc/devinfra-agent"
    },
    {
      "name": "vscode-ext-scratch",
      "repo_url": "https://github.com/devzero-inc/vscode-ext-scratch"
    },
    {
      "name": "did",
      "repo_url": "https://github.com/devzero-inc/did"
    },
    {
      "name": "authproxy",
      "repo_url": "https://github.com/devzero-inc/authproxy"
    },
    {
      "name": "dzadm",
      "repo_url": "https://github.com/devzero-inc/dzadm"
    },
    {
      "name": "dz-cli",
      "repo_url": "https://github.com/devzero-inc/dz-cli"
    },
    {
      "name": "services",
      "repo_url": "https://github.com/devzero-inc/services"
    },
    {
      "name": "dz-helper",
      "repo_url": "https://github.com/devzero-inc/dz-helper"
    },
    {
      "name": "db-shell",
      "repo_url": "https://github.com/devzero-inc/db-shell"
    },
    {
      "name": "terraform",
      "repo_url": "https://github.com/devzero-inc/terraform"
    },
    {
      "name": "privateGPT",
      "repo_url": "https://github.com/devzero-examples/privateGPT"
    }
  ],
  "author": {
    "name": "Lauren"
  },
  "packages": ["nodejs-16_x", "pnpm-7_x", "openssl"],
  "commands": [
    {
      "shell": "pnpm i --frozen-lockfile",
      "name": "install cmd",
      "directory": "nextjs-pg"
    }
  ]
}

=== devzero-inc/workspace-recipe-library/workspaces/sample4.json
{
  "id": "4",
  "name": "Recipe 4",
  "description": "Here is a template for that",
  "cover_image": "https://picsum.photos/700/400",
  "repos": [
    {
      "name": "devzero-website",
      "repo_url": "https://github.com/devzero-inc/devzero-website"
    }
  ],
  "author": {
    "name": "DevZero"
  },
  "packages": ["nodejs-16_x", "pnpm-7_x", "openssl"],
  "commands": [
    {
      "shell": "pnpm i --frozen-lockfile",
      "name": "install cmd",
      "directory": "nextjs-pg"
    }
  ]
}

=== devzero-inc/workspace-recipe-library/workspaces/sample2.json
{
  "id": "2",
  "name": "Sample",
  "cover_image": "https://camo.githubusercontent.com/4f1c7189be171d34a36011cb48f165c4023850598a07e4c9c826531b6705b77e/68747470733a2f2f636c6f75642e676f6f676c652e636f6d2f636f64652f646f63732f7673636f64652f696d616765732f6372656174652d6e65772d6170702e676966",
  "description": "Get started with DevZero! This is a sample recipe containing node. There are also a few spiders in here. Not poisonous ones, mind you, but they do look scary and they're a little mad. Try not to make any sudden movemen- oh no. There were supposed to be 8 in here and I only count 7",
  "repos": [
    {
      "name": "devzero-website",
      "repo_url": "https://github.com/devzero-inc/devzero-website"
    }
  ],
  "author": {
    "name": "DevZero"
  },
  "packages": ["nodejs-16_x", "pnpm-7_x", "openssl"],
  "commands": [
    {
      "shell": "pnpm i --frozen-lockfile",
      "name": "install cmd",
      "directory": "nextjs-pg"
    }
  ]
}

=== devzero-inc/workspace-recipe-library/workspaces/sample1.json
{
  "id": "1",
  "name": "Recipe 1",
  "description": "Here is a template for this",
  "cover_image": "https://placebear.com/700/400",
  "repos": [
    {
      "name": "devzero-website",
      "repo_url": "https://github.com/devzero-inc/devzero-website"
    }
  ],
  "author": {
    "name": "DevZero"
  },
  "packages": ["nodejs-16_x", "pnpm-7_x", "openssl"],
  "commands": [
    {
      "shell": "pnpm i --frozen-lockfile",
      "name": "install cmd",
      "directory": "nextjs-pg"
    }
  ]
}
